apiVersion: apps/v1
kind: Deployment
metadata:
spec:
  replicas: 2
  selector:
    matchLabels:
      app: accounts
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    spec:
      containers:
      - image: kowshhal/accounts
        imagePullPolicy: Always
        name: accounts
      restartPolicy: Always
---
apiVersion: v1
kind: Service
  metadata:
  spec:
    clusterIP: 10.152.183.203
    externalTrafficPolicy: Cluster
    ports:
    - nodePort: 32639
      port: 5000
      protocol: TCP
      targetPort: 5000
    selector:
      app: accounts
    type: NodePort
  
